### ISSUE TITLE
Setup python environment

### ISSUE THREAD

**Issue by Shaheerairaj** [Shaheerairaj/car-value-estimator-team#1]
Functionality:
- Take in a list of car brands to scrape data for
- Capture all data for each ad from the listing page
- Iterate through all listing pages to capture data for all ads

**Comment by ohinson01** [comment]
**2024-MAY-14**

Just to document here. 

Python environment is set up on my machine. Installed Selenium and downloaded the webdriver to use for project (Google Chrome webdriver).

**Comment by Shaheerairaj** [comment]
Good progress you're making Olivia. Love how you're constantly in communication.
