### ISSUE TITLE
Feature correlation and distribution analysis

### ISSUE THREAD

**Issue by Shaheerairaj** [Shaheerairaj/car-value-estimator-team#9]

**Comment by ChitiNkhuwa** [comment]
I will get started on this, I believe it can be done concurrently at the same time as what Anna is doing on phase 2.

**Comment by ChitiNkhuwa** [comment]
@Shaheerairaj  I created a new pull request, kindly let me know if you can see it.

**Comment by Shaheerairaj** [comment]
Hey Chiti. Sorry, I'm just seeing this now but I don't see any PRs raised.
